server:
  port: 9192

spring:
  datasource: 
    username: sa
    password: sa
    url: jdbc:sqlserver://localhost;databaseName=bookingHotel;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 5MB
      file-size-threshold: 2KB
  security:
    jwt:
      secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
      expire-length: 3600000
